version: '3'
services:

  ussum-develop:
    image: ${DOCKER_REPO}/ussum-develop:latest
    logging:
      driver: syslog
    environment:
      - TZ=Asia/Seoul
      - SPRING_CONFIG_LOCATION=file:/app/application.yml
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/application.yml:/app/application.yml
    networks:
      - dev-homepage-network

  redis-server:
    container_name: redis-server
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dev-homepage-network


networks:
  dev-homepage-network:
    driver: bridge