version: '3'
services:
  blue:
    container_name: blue
    image: haul123/blue-green
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_CONFIG_LOCATION=file:/app/application.yml
    volumes:
      - /var/log/homepage:/var/log/homepage # /var/log/homepage
      - /home/ubuntu/application.yml:/app/application.yml
  green:
    container_name: green
    image: haul123/blue-green
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_CONFIG_LOCATION=file:/app/application.yml
    volumes:
      - /var/log/homepage:/var/log/homepage # /var/log/homepage
      - /home/ubuntu/application.yml:/app/application.yml
