version: '3'
services:
  blue:
    container_name: blue
    image: ssuitspecial/blue-green
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/log/homepage:/var/log/homepage # /var/log/homepage
  green:
    container_name: green
    image: ssuitspecial/blue-green
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/log/homepage:/var/log/homepage # /var/log/homepage
