package ussum.homepage.infra.jpa.member.entity;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import ussum.homepage.global.error.exception.InvalidValueException;

import java.util.Arrays;

import static ussum.homepage.global.error.status.ErrorStatus.INVALID_MEMBERCODE;

@RequiredArgsConstructor
@Getter
public enum MemberCode {
    // 총학생회
    STUDENT_COUNCIL("STUDENT_COUNCIL"),

    // 중앙운영위원회
    CENTRAL_OPERATION_COMMITTEE("CENTRAL_OPERATION_COMMITTEE"),

    // 동아리연합회
    CLUB_UNION("CLUB_UNION"),

    // 중앙선거관리위원회
    CENTRAL_ELECTION_COMMITTEE("CENTRAL_ELECTION_COMMITTEE"),

    // 경영대학선거관리위원회
    BUSINESS_SCHOOL_ELECTION_COMMITTEE("BUSINESS_SCHOOL_ELECTION_COMMITTEE"),

    // 경제통상대학선거관리위원회
    ECONOMICS_TRADE_SCHOOL_ELECTION_COMMITTEE("ECONOMICS_TRADE_SCHOOL_ELECTION_COMMITTEE"),

    // 공과대학선거관리위원회
    ENGINEERING_SCHOOL_ELECTION_COMMITTEE("ENGINEERING_SCHOOL_ELECTION_COMMITTEE"),

    // 법과대학선거관리위원회
    LAW_SCHOOL_ELECTION_COMMITTEE("LAW_SCHOOL_ELECTION_COMMITTEE"),

    // 사회과학대학선거관리위원회
    SOCIAL_SCIENCES_SCHOOL_ELECTION_COMMITTEE("SOCIAL_SCIENCES_SCHOOL_ELECTION_COMMITTEE"),

    // 인문대학선거관리위원회
    HUMANITIES_SCHOOL_ELECTION_COMMITTEE("HUMANITIES_SCHOOL_ELECTION_COMMITTEE"),

    // 자연과학대학선거관리위원회
    NATURAL_SCIENCES_SCHOOL_ELECTION_COMMITTEE("NATURAL_SCIENCES_SCHOOL_ELECTION_COMMITTEE"),

    // IT대학선거관리위원회
    IT_SCHOOL_ELECTION_COMMITTEE("IT_SCHOOL_ELECTION_COMMITTEE"),

    // 동아리연합회선거관리위원회
    CLUB_UNION_ELECTION_COMMITTEE("CLUB_UNION_ELECTION_COMMITTEE"),

    // 중앙감사위원회
    CENTRAL_AUDIT_COMMITTEE("CENTRAL_AUDIT_COMMITTEE"),

    // 경영대학감사위원회
    BUSINESS_SCHOOL_AUDIT_COMMITTEE("BUSINESS_SCHOOL_AUDIT_COMMITTEE"),

    // 경제통상대학감사위원회
    ECONOMICS_TRADE_SCHOOL_AUDIT_COMMITTEE("ECONOMICS_TRADE_SCHOOL_AUDIT_COMMITTEE"),

    // 공과대학감사위원회
    ENGINEERING_SCHOOL_AUDIT_COMMITTEE("ENGINEERING_SCHOOL_AUDIT_COMMITTEE"),

    // 법과대학감사위원회
    LAW_SCHOOL_AUDIT_COMMITTEE("LAW_SCHOOL_AUDIT_COMMITTEE"),

    // 사회과학대학감사위원회
    SOCIAL_SCIENCES_SCHOOL_AUDIT_COMMITTEE("SOCIAL_SCIENCES_SCHOOL_AUDIT_COMMITTEE"),

    // 인문대학감사위원회
    HUMANITIES_SCHOOL_AUDIT_COMMITTEE("HUMANITIES_SCHOOL_AUDIT_COMMITTEE"),

    // 자연과학대학감사위원회
    NATURAL_SCIENCES_SCHOOL_AUDIT_COMMITTEE("NATURAL_SCIENCES_SCHOOL_AUDIT_COMMITTEE"),

    // IT대학감사위원회
    IT_SCHOOL_AUDIT_COMMITTEE("IT_SCHOOL_AUDIT_COMMITTEE"),

    // 경영대학
    BUSINESS_SCHOOL("BUSINESS_SCHOOL"),

    // 경제통상대학
    ECONOMICS_TRADE_SCHOOL("ECONOMICS_TRADE_SCHOOL"),

    // 공과대학
    ENGINEERING_SCHOOL("ENGINEERING_SCHOOL"),

    // 법과대학
    LAW_SCHOOL("LAW_SCHOOL"),

    // 사회과학대학
    SOCIAL_SCIENCES_SCHOOL("SOCIAL_SCIENCES_SCHOOL"),

    // 인문대학
    HUMANITIES_SCHOOL("HUMANITIES_SCHOOL"),

    // 자연과학대학
    NATURAL_SCIENCES_SCHOOL("NATURAL_SCIENCES_SCHOOL"),

    // IT대학
    IT_SCHOOL("IT_SCHOOL"),

    // 융합특성화자유전공학부
    CONVERGENCE_DEPARTMENT("INTERDISCIPLINARY_STUDIES_DEPARTMENT"),

    // 학생인권위원회
    STUDENT_HUMAN_RIGHTS_COMMITTEE("STUDENT_HUMAN_RIGHTS_COMMITTEE"),

    // 교지편집위원회
    SCHOOL_MAGAZINE_EDITORIAL_COMMITTEE("SCHOOL_MAGAZINE_EDITORIAL_COMMITTEE"),

    // 학생복지위원회
    STUDENT_WELFARE_COMMITTEE("STUDENT_WELFARE_COMMITTEE"),

    // IT지원위원회
    IT_SUPPORT_COMMITTEE("IT_SUPPORT_COMMITTEE"),

    // 학생서비스팀
    STUDENT_SERVICES_TEAM("STUDENT_SERVICES_TEAM");

    private final String stringMemberCode;
    public static MemberCode getEnumMemberCodeFromStringMemberCode(String stringMemberCode) {
        return Arrays.stream(values())
                .filter(memberCode -> memberCode.stringMemberCode.equals(stringMemberCode))
                .findFirst()
                .orElseThrow(() -> new InvalidValueException(INVALID_MEMBERCODE));
    }

}
